### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by SylverSK40** [andburn/hdt-plugin-victoryshot#1]
I've been having and issue where the screenshots taken are black.

**Comment by andburn** [comment]
Hi, not sure what could be causing this. Does it happen every time?

Try this,
- Go to the options in the Deck Tracker
- Enable Advanced options at the bottom
- Go to Hotkeys
- Setup up Hotkeys for `Screenshot` and `Game Screenshot`
- *You should have something like the screenshot below*
- Now with Hearthstone active, take screenshots using both the hotkeys you setup
- Let me know if these screenshots are ok

![hdt-shortcuts](https://user-images.githubusercontent.com/5419653/45054275-64e98f80-b084-11e8-8f5e-3cd0eeb2289b.png)

**Comment by SylverSK40** [comment]
Okay when I do Alt+Z I get a clear screenshot but when I do Alt+X the screenshot is all black.
![hearthstone 09-04-18 07-58-46](https://user-images.githubusercontent.com/8241530/45063707-521f8c80-b07d-11e8-9db6-19e26f464bd1.png)
![hearthstone 09-04-18 07-59-11](https://user-images.githubusercontent.com/8241530/45063708-521f8c80-b07d-11e8-99dc-add2f3e25d2d.png)

**Comment by andburn** [comment]
Ok, try this version [hdt-plugin-victoryshot.zip](https://github.com/andburn/hdt-plugin-victoryshot/files/2354654/hdt-plugin-victoryshot.zip)

You need to go to the plugins settings and **uncheck** the box at the bottom that says '*Use alternative image capture*'. Hopefully, that will fix it.

**Comment by SylverSK40** [comment]
Yep that worked perfectly, thanks again for the quick response.
